// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Admin struct {
	ID         string `json:"_id"`
	MatrixID   string `json:"matrixID"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	Privilidge bool   `json:"privilidge"`
}

type Block struct {
	Num      int    `json:"_num"`
	MatrixID string `json:"matrixID"`
	UserID   string `json:"userID"`
	Nounce   int    `json:"nounce"`
	Data     string `json:"data"`
	Prev     string `json:"prev"`
	Current  string `json:"current"`
}

type Matrix struct {
	ID            string      `json:"_id"`
	Name          string      `json:"name"`
	Mongodatabase interface{} `json:"mongodatabase"`
	Userdatabase  interface{} `json:"userdatabase"`
	Admindatabase interface{} `json:"admindatabase"`
}

type User struct {
	ID                string      `json:"_id"`
	MatrixID          string      `json:"matrixID"`
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	Password          string      `json:"password"`
	CurrentBalance    float64     `json:"current_balance"`
	Usermongodatabase interface{} `json:"usermongodatabase"`
}
