// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model
import "gorm.io/gorm"

type Admin struct {
	gorm.Model
	ID            string  `gorm:"primaryKey" json:"_id"`
	MatrixID      string  `gorm:"unique" json:"matrixID"`
	Username      string  `gorm:"unique" json:"username"`
	Email         string  `gorm:"unique" json:"email"`
	Password      string  `gorm:"unique" json:"password"`
	Privilidge    bool    `json:"privilidge"`
	ReleaseFlow   float64 `json:"releaseFlow"`
	TotalCurrency float64 `json:"totalCurrency"`
	SetRate       float64 `json:"setRate"`
}

type Block struct {
	Num      int    `json:"_num" bson:"_num,omitempty"`
	MatrixID string `json:"matrixID" bson:"matrixID"`
	UserID   string `json:"userID" bson:"userID"`
	Nounce   int    `json:"nounce" bson:"nounce"`
	Data     *Data  `json:"data" bson:"data"`
	Prev     string `json:"prev" bson:"prev"`
	Current  string `json:"current" bson:"current"`
	Verify   bool   `json:"verify" bson:"verify"`
}

type BlockType struct {
	Num     int       `json:"_num" bson:"_num,omitempty"`
	Nounce  int       `json:"nounce" bson:"nounce"`
	Data    *DataType `json:"data" bson:"data"`
	Prev    string    `json:"prev" bson:"prev"`
	Current string    `json:"current" bson:"current"`
	Verify  bool      `json:"verify" bson:"verify"`
}

type CurrentTransaction struct {
	Block   *Block  `json:"block" bson:"block"`
	Percent float64 `json:"percent" bson:"percent"`
	Status  bool    `json:"status" bson:"status"`
}

type Data struct {
	From   string  `json:"from" bson:"from"`
	To     string  `json:"to" bson:"to"`
	Amount float64 `json:"amount" bson:"amount"`
}

type DataType struct {
	From   string  `json:"from" bson:"from"`
	To     string  `json:"to" bson:"to"`
	Amount float64 `json:"amount" bson:"amount"`
}

type Matrix struct {
	gorm.Model
	ID   string `gorm:"primaryKey" json:"_id"`
	Name string `gorm:"unique" json:"name"`
}

type User struct {
	gorm.Model
	ID             string  `gorm:"primaryKey" json:"_id"`
	MatrixID       string  `json:"matrixID"`
	Username       string  `gorm:"unique" json:"username"`
	Email          string  `gorm:"unique" json:"email"`
	Password       string  `gorm:"unique" json:"password"`
	CurrentBalance float64 `json:"current_balance"`
}

type VerifyAdminResult struct {
	Verify bool   `json:"verify"`
	Admin  *Admin `json:"admin"`
}

type VerifyUserResult struct {
	Verify bool  `json:"verify"`
	User   *User `json:"user"`
}
